name: build-calendar

on: [workflow_dispatch]

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3

```
  - run: pip install lunardate

  - run: python generate.py

  - run: |
      git config --global user.name "bot"
      git config --global user.email "bot@github.com"
      git add calendar.ics
      git commit -m "update" || echo ok
      git push
```
